FORMAT: 1A

# letsencrypt-heroku

letsencrypt-heroku is an API which allows you to provision SSL certificate using letsencrypt and Heroku.

Free. Forever.

## Certificate Generation [/certificate_generation/new/{domain_name}]

### Provision a New Certificate [GET]

Provision a new SSL certificate using this endpoint.

+ Parameters
    + domain_name (string) - The domain to be secured. This should also be the name of a CloudFlare zone.
    + subdomains (string) - Comma delimited list of subdomains to secure. Usually contains `www`.
    + debug (integer, optional) - `1` if using the letsencrypt staging endpoint. Recommended for testing.
    + app_name (string) - The name of the Heroku application to be secured.
    + auth_token (string) - AUTH TOKEN value.


+ Response 201 (application/json)

    + Body

            {
                status_path: "https://host/certificate_generation/3911dd66aade4cfdf9dd1d0e1cebde87"
            }


## Certificate Generation Status [/certificate_generation/{token}]
### Get Provisioning Status [GET]

Get status of certificate provisioning.

+ Parameters
    + token (string) - Unique token for provisioning.
    + auth_token (string) - AUTH TOKEN value



+ Response 201 (application/json)

    + Body

            {
                token: "3911dd66aade4cfdf9dd1d0e1cebde87",
                status: "success",
                error: null,
                domain: "substrakt.com",
                subdomains: [
                    "www",
                    "www3"
                ],
                message: "Done"
            }